version: '2'
services:
  fleet-supervisor:
    build: ./fleet-supervisor
    restart: always
    network_mode: host
    privileged: true
    ports:
      - 3000:3000
    labels:
      io.balena.features.supervisor-api: 1
  bluetooth-audio:
    build: ./bluetooth-audio
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - bluetoothcache:/var/cache/bluetooth
      - snapcast:/var/cache/snapcast
  airplay:
    build: ./airplay
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - snapcast:/var/cache/snapcast
  spotify:
    build: ./spotify
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - spotifycache:/var/cache/raspotify
      - snapcast:/var/cache/snapcast
  snapcast-server:
    build: ./snapcast-server
    restart: always
    ports:
      - 1704:1704
      - 1705:1705
    volumes:
      - snapcast:/var/cache/snapcast
  snapcast-client:
    build: ./snapcast-client
    restart: always 
    network_mode: host 
    privileged: true
    volumes:
      - snapcast:/var/cache/snapcast
volumes:
  spotifycache:
  bluetoothcache:
  snapcast:
