version: '2'
services:
  fleet-supervisor:
    build: ./fleet-supervisor
    network_mode: host
    labels:
      io.balena.features.supervisor-api: 1
  bluetooth-audio:
    network_mode: host
    restart: always
    build: ./bluetooth-audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - bluetoothcache:/var/cache/bluetooth
      - snapcast:/var/cache/snapcast
  airplay:
    build: ./airplay
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - snapcast:/var/cache/snapcast
  spotify:
    build: ./spotify
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - spotifycache:/var/cache/raspotify
      - snapcast:/var/cache/snapcast
  snapcast-server:
    build: ./snapcast-server
    privileged: true
    network_mode: host   
    labels:
      io.balena.features.dbus: 1
    volumes:
      - snapcast:/var/cache/snapcast
  snapcast-client:
    build: ./snapcast-client
    privileged: true
    network_mode: host   
    labels:
      io.balena.features.dbus: 1
    volumes:
      - snapcast:/var/cache/snapcast
volumes:
  spotifycache:
  bluetoothcache:
  snapcast:
